version: '3.8'

services:
  postgres-product:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: gelato_user
      POSTGRES_PASSWORD: gelato_pass
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: gelato_user
      POSTGRES_PASSWORD: gelato_pass
    ports:
      - "5433:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://gelato_user:gelato_pass@postgres-product:5432/product_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres-product
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://gelato_user:gelato_pass@postgres-order:5432/order_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres-order
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - product-service
      - order-service

volumes:
  product_data:
  order_data: